[docstub]
extend_grammar = """

"""

[docstub.replace_map]
numpy = "np"
uint8 = "np.uint8"
array-like = "ArrayLike"
array_like = "ArrayLike"
ndarray = "NDArray"
array = "NDArray"

# trigger = "[<from>]::<import>[::<alias>]"
[docstub.import_map]
np = "::numpy::np"
ArrayLike = "numpy.typing::ArrayLike"
NDArray = "numpy.typing::NDArray"
Union = "typing::Union"
