[docstub]
extend_grammar = """

"""


[docstub.docnames]
np = { import = "numpy", as = "np" }
uint8 = { use = "np.uint8", import = "numpy", as = "np" }
ArrayLike = { from = "numpy.typing" }
NDArray = { from = "numpy.typing" }
Union = { from = "typing" }
